apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azurereleaseproj
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azurek8
subjects:
- kind: ServiceAccount
  name: azurerelease
  namespace: default
